[package]
name = "ui"
version = "0.1.0"
authors = ["brandonrichey"]
edition = "2018"

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
yew = "0.17"
wasm-bindgen = "0.2.58"
anyhow = "1.0"
serde = "1.0"